services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "3000:3000"
  
  nginx:
    image: nginx:1.19.8-alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-init.d:/etc/nginx/conf.d
      - ./nginx/etc/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    restart: always
  
  # certbot запускается для получения сертификатов
  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - ./nginx/etc/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email andrey2455@gmail.com --agree-tos --no-eff-email -d www.dolina.axonix.ru -d dolina.axonix.ru