version: '3.9'

services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "3000:3000"
  
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-conf.d/:/etc/nginx/conf.d
      - ./nginx/etc/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    restart: always
  
  # certbot запускается для мониторинга сертификатов.
  # Каждые 12 часов выполняется команда certbot renew.
  # Если сертификаты скоро закончатся, то запрашивается выпуск новых.
  # После этого перезагружается nginx.
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - ./nginx/etc/letsencrypt:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; nginx -s reload; sleep 12h; done'"